<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Paystub Creator</title>

</head>

<body>

    <table style="width:100%; max-width:620px; margin: 0 auto; border: solid 1px #D4D4D4; table-layout: fixed;" cellspacing="0">
        <tr>
            <td style=" background: #98a2c5; width: 120px; vertical-align: top;">
                <div style="width: 100%; min-height: 100px; float: left; text-align: center; border-radius: 5px;">
                    <img style="max-width: 100%; max-height: 100px;" id="company_logo_url_id" src="{[logo_url]}">
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <table style="padding: 15px;">
                    <tr>
                        <td id="email_content_part_id">
                            <h5 style="font-size: 14px; color: #333; margin-top: 0px;text-align:left">Hello</h5>
                            <p style="font-size: 14px; margin-bottom: 30px;">The first part of this email is a message generated by PDF Writer. It tells what the recipient is getting, who has sent it to them and if you have requested an eSignature.</p>
                            <p style="font-size: 14px; margin-bottom: 30px;">The second part of this email is a message that you can create whenever you share a document or request a signature.</p>
                            <p style="font-size: 14px; margin-bottom: 30px;">The last part of this email is generated by PDF Writer and will include instructions on how to access the document and a direct link. It may also contain password reset or support information.</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="border-top:solid 1px #ddd; padding-top: 20px;">
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[name]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[title]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[company]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[email]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[phone]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[fax]}</p>
                            <p style="color: #212529; font-size: 14px; margin-bottom: 5px; margin-top: 0px;">{[website]}</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>