<div style="padding:15px;">
    <h4>Hello</h4>
    <p>Third The first part of this email is a message generated by PDF Writer. It tells what the recipient is getting, who has sent it to them and if you have requested an eSignature.</p>
    <p> The second part of this email is a message that you can create whenever you share a document or request a signature.</p>
    <p> The last part of this email is generated by PDF Writer and will include instructions on how to access the document and a direct link. It may also contain password reset or support information.</p>
    <div class="hide" style="margin-top:20px">
        <p style="margin-bottom:0px">{[name]}</p>
        <p style="margin-bottom:0px">{[title]}</p>
        <p style="margin-bottom:0px">{[title]}</p>
        <p style="margin-bottom:0px">{[company]}</p>
        <p style="margin-bottom:0px">{[email]}</p>
        <p style="margin-bottom:0px">{[phone]}</p>
        <p style="margin-bottom:0px">{[fax]}</p>
    </div>
</div>